In [1]:
import numpy as np
import tensorflow as tf

In [2]:
print (tf.__version__)

1.15.0


## Defining Tensors

In [6]:
m1 = [[1.0, 2.0], 
      [3.0, 4.0]]
m2 = np.array([[1.0, 2.0],
              [3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

In [7]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [8]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [9]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [10]:
sess = tf.Session()
print ("OPEN SESSION")

OPEN SESSION


In [11]:
def print_tf(x):
    print("TYPE IS\n %s" % (type(x)))
    print("VALUE IS\n %s" % (x))

## Constants

In [12]:
hello = tf.constant("Hello World!")
print(hello)
print_tf(hello)

Tensor("Const_5:0", shape=(), dtype=string)
TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_5:0", shape=(), dtype=string)


In [13]:
hello_out = sess.run(hello)
print_tf(hello_out)

TYPE IS
 <class 'bytes'>
VALUE IS
 b'Hello World!'


In [14]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_6:0", shape=(), dtype=float32)
TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_7:0", shape=(), dtype=float32)


In [15]:
a_out = sess.run(a)
b_out = sess.run(b)
print_tf(a_out)
print_tf(b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 1.5
TYPE IS
 <class 'numpy.float32'>
VALUE IS
 2.5


## Operations

In [16]:
a_plus_b = tf.add(a, b)
print_tf(a_plus_b)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Add:0", shape=(), dtype=float32)


In [17]:
a_plus_b_out = sess.run(a_plus_b)
print_tf(a_plus_b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 4.0


In [18]:
a_mul_b = tf.multiply(a, b)
a_mul_b_out = sess.run(a_mul_b)
print_tf(a_mul_b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 3.75


## Variables

In [19]:
weight = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight)

TYPE IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS
 <tf.Variable 'Variable:0' shape=(5, 2) dtype=float32_ref>


In [20]:
tf.Variable?

In [21]:
weight_out = sess.run(weight)
print_tf(weight_out)

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[{{node _retval_Variable_0_0}}]]

In [22]:
sess.run(weight.initializer)

In [23]:
weight_out = sess.run(weight)
print_tf(weight_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[ 0.08054729 -0.03190583]
 [-0.07639687  0.03098414]
 [ 0.1400496   0.03824809]
 [-0.09372032  0.10630768]
 [-0.14761491  0.06911507]]


In [24]:
weight2 = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
weight3 = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight2)
print_tf(weight3)

TYPE IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS
 <tf.Variable 'Variable_1:0' shape=(5, 2) dtype=float32_ref>
TYPE IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS
 <tf.Variable 'Variable_2:0' shape=(5, 2) dtype=float32_ref>


In [25]:
init = tf.global_variables_initializer()
sess.run(init)

In [26]:
weight_out2 = sess.run(weight2)
weight_out3 = sess.run(weight3)
print_tf(weight_out2)
print_tf(weight_out3)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.03470379  0.03591319]
 [ 0.12051763 -0.03136274]
 [ 0.00875983  0.04535694]
 [ 0.11949314  0.0893733 ]
 [-0.04536536  0.11352279]]
TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.19616525  0.0676393 ]
 [ 0.11318012 -0.18099147]
 [-0.08303359  0.04906156]
 [ 0.11057643  0.07616691]
 [ 0.08610563  0.09374141]]


In [3]:
s = tf.Variable(2, name='scalar') 
m = tf.Variable([[0, 1], [2, 3]], name='matrix') 
W = tf.Variable(tf.zeros([784,10]), name='big_matrix')
V = tf.Variable(tf.truncated_normal([784, 10]), name='normal_matrix')

s = tf.get_variable('scalar', initializer=tf.constant(3)) 
m = tf.get_variable('matrix', initializer=tf.constant([[10, 11], [2, 3]]))
W = tf.get_variable('big_matrix', shape=(784, 20), initializer=tf.zeros_initializer())
V = tf.get_variable('normal_matrix', shape=(784, 5), initializer=tf.truncated_normal_initializer())

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(V.eval())

[[ 0.32562792  0.00629753 -1.1451399  -0.50684303 -0.8963494 ]
 [-0.3077097  -0.14516059  0.56119764 -0.21298     1.1965606 ]
 [ 1.7264265  -0.73451334  0.01652726 -0.57061034  1.2947953 ]
 ...
 [-1.5088776  -0.29114464 -0.4851858  -0.47567505  0.11089993]
 [-0.43739203 -1.915957   -1.0420249  -1.5389191  -0.04682865]
 [ 0.23198986  0.5566814  -0.12086448 -1.028522   -1.2851608 ]]


In [27]:
s = tf.Variable(2, name='scalar') 
m = tf.Variable([[0, 1], [2, 3]], name='matrix') 
W = tf.Variable(tf.zeros([784,10]), name='big_matrix')
V = tf.Variable(tf.truncated_normal([784, 10]), name='normal_matrix')

s = tf.get_variable('scalar', initializer=tf.constant(2)) 
m = tf.get_variable('matrix', initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable('big_matrix', shape=(784, 10), initializer=tf.zeros_initializer())
V = tf.get_variable('normal_matrix', shape=(784, 10), initializer=tf.truncated_normal_initializer())

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(V.eval())

ValueError: Variable scalar already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Users\shkim\Anaconda3\envs\rnn\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
  File "C:\Users\shkim\Anaconda3\envs\rnn\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\shkim\Anaconda3\envs\rnn\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\shkim\Anaconda3\envs\rnn\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\shkim\Anaconda3\envs\rnn\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)


In [4]:
V.shape

TensorShape([Dimension(784), Dimension(5)])

## Placeholders

In [28]:
x = tf.placeholder(tf.float32, [None, 5])
print_tf(x)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Placeholder_1:0", shape=(?, 5), dtype=float32)


In [29]:
oper = tf.matmul(x, weight)
print_tf(oper)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("MatMul:0", shape=(?, 2), dtype=float32)


In [30]:
#sess = tf.Session()
data = np.random.rand(1, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.15077813  0.03677043]]


In [31]:
data = np.random.rand(2, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.35666278  0.10107143]
 [-0.23022774  0.06262599]]


In [32]:
sess.close()