In [ ]:
# try:
#   # %tensorflow_version only exists in Colab.
#   %tensorflow_version 2.x
# except Exception:
#   pass
# import tensorflow as tf

In [21]:
import numpy as np
import tensorflow as tf

In [22]:
print (tf.__version__)

2.0.0


In [23]:
tf.executing_eagerly()

True

## Defining Tensors

In [24]:
m1 = [[1.0, 2.0], 
      [3.0, 4.0]]
m2 = np.array([[1.0, 2.0],
              [3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

In [25]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [26]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [27]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [28]:
print(t1)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


## Numpy Compatibility

In [29]:
ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)


print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())
print(ndarray)

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Constants

In [30]:
hello = tf.constant("Hello World!")
print(hello)

tf.Tensor(b'Hello World!', shape=(), dtype=string)


In [31]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print(a.numpy())
print(b)

1.5
tf.Tensor(2.5, shape=(), dtype=float32)


## Operations

In [32]:
a_plus_b = tf.add(a, b)
print(a_plus_b)

tf.Tensor(4.0, shape=(), dtype=float32)


In [33]:
a_mul_b = tf.multiply(a, b)
print(a_mul_b)
print(a_mul_b.numpy())

tf.Tensor(3.75, shape=(), dtype=float32)
3.75


## Variables

In [34]:
weight = tf.Variable(tf.random_normal_initializer(stddev=0.1)([5, 2]))
print(weight)

<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[ 0.03261365,  0.00715874],
       [ 0.02579087,  0.0581035 ],
       [-0.05888956,  0.0417898 ],
       [ 0.09966046,  0.06044535],
       [-0.04622089, -0.11697084]], dtype=float32)>


## Create a Dataset

In [35]:
a = np.arange(10)
print(a)
ds_tensors = tf.data.Dataset.from_tensor_slices(a)
# ds_tensors = tf.data.Dataset.from_tensor_slices(a).map(tf.square).shuffle(20).batch(2)
print(ds_tensors)

[0 1 2 3 4 5 6 7 8 9]
<TensorSliceDataset shapes: (), types: tf.int32>


## Apply Transformations

In [36]:
# ds_tensors = ds_tensors.map(tf.square).batch(2)
ds_tensors = ds_tensors.map(tf.square).shuffle(20).batch(2)
ds_tensors

<BatchDataset shapes: (None,), types: tf.int32>

## Iterate

In [37]:
print('Elements of ds_tensors:')
for _ in range(3):
  for x in ds_tensors:
    print(x)

Elements of ds_tensors:
tf.Tensor([36 16], shape=(2,), dtype=int32)
tf.Tensor([ 4 81], shape=(2,), dtype=int32)
tf.Tensor([25  9], shape=(2,), dtype=int32)
tf.Tensor([64  1], shape=(2,), dtype=int32)
tf.Tensor([ 0 49], shape=(2,), dtype=int32)
tf.Tensor([81 64], shape=(2,), dtype=int32)
tf.Tensor([16 36], shape=(2,), dtype=int32)
tf.Tensor([25 49], shape=(2,), dtype=int32)
tf.Tensor([4 0], shape=(2,), dtype=int32)
tf.Tensor([9 1], shape=(2,), dtype=int32)
tf.Tensor([81 36], shape=(2,), dtype=int32)
tf.Tensor([25 64], shape=(2,), dtype=int32)
tf.Tensor([16  9], shape=(2,), dtype=int32)
tf.Tensor([49  0], shape=(2,), dtype=int32)
tf.Tensor([4 1], shape=(2,), dtype=int32)


In [38]:
print('Elements of ds_tensors:')
for _ in range(3):
  for x in ds_tensors.take(2):
    print(x)

Elements of ds_tensors:
tf.Tensor([81  1], shape=(2,), dtype=int32)
tf.Tensor([ 0 36], shape=(2,), dtype=int32)
tf.Tensor([ 4 16], shape=(2,), dtype=int32)
tf.Tensor([81  9], shape=(2,), dtype=int32)
tf.Tensor([ 0 16], shape=(2,), dtype=int32)
tf.Tensor([25  4], shape=(2,), dtype=int32)
